import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { TextProvider } from "@/context/textProvider";
import Header from "@/components/AppHeader";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <TextProvider>
        <body
          className={`${geistSans.variable} bg-[#150002] ${geistMono.variable} antialiased`}
        >
          <Header />

          {children}
        </body>
      </TextProvider>
    </html>
  );
}
